backend:
  name: git-gateway
  branch: master # 要更新的分支(可选；默认为主分支)
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'


logo_url: /favicon.svg # 你的 logo


# 禁用部署预览链接
show_preview_links: true


# This line should *not* be indented
publish_mode: editorial_workflow


# This line should *not* be indented
media_folder: "/exampleSite/static/images/" # 媒体文件将存储在图片/上载下的Repo中。
public_folder: "/images" # 上传的媒体的src属性将以/images/uploads开头。


site_url: https://wei-site.netlify.app/ # 网站网址
display_url: https://wei-site.netlify.app/ # 显示网址


locale: "zh_Hans" # 语言环境


collections: 
  - name: "posts" # 在路由中使用，例如：/admin/collections/blog。
    label: "Posts" # 在用户界面中使用
    folder: "/exampleSite/content/blogs/" # 存储文件的文件夹的路径。
    # filter: {field: "categories", value: "Posts"} # 筛选
    create: true # 允许用户在这个集合中创建新的文件。
    fields: # 每份文件的字段，通常是前面的内容。
      - {label: "Title", name: "title", widget: "string", required: true}
      - {date: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: true}
      - {author: "Author", name: "author", widget: "string", required: true}
      - {tags: "Tags", name: "tags", widget: "list", required: true}
      - {image: "Main image", name: "image", widget: "image", required: false}
      - {description: "Abstract", name: "description", required: true}
      - {toc: "Table of Contents", name: "toc", widget: "boolean", default: true, required: true}
      - {mathjax: "Mathjax", name: "mathjax", widget: "boolean", default: true}
      - {content: "Content", name: "body", widget: "markdown", required: true}

